### ISSUE TITLE
Data API Docs

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeDocs#335]
The Data API Docs have commenced to exist, but as gabizou put it so aptly, they merely scratch the tip of the Iceberg. Since the Data API is such a prominent feature of Sponge it deserves thorough explanation, which is mainly why the currently existing docs cover only a part of what I originally intended to write about. I'll continue to dive into the API and once I've understood enough, come back to add another page to the docs. I can in no way give an ETA or anything, so I present my To Do list here, with unmarked items free for anyone to give a shot at. 

To Do List:
- [ ] Basic stuff
 - [x] Using `Key`s to retrieve and alter Data (#331)
 - [x] Using keyed `Value`s (#331)
 - [x] `DataManipulator` usage (#331)
 - [x] Getting Information from a `DataTransactionResult` (#331)
 - [ ] Persistence / Serialization Tools (`DataContainer`, `DataBuilder`)
-  [ ] advanced Applications
 - [ ] Using existing `DataManipulators` on custom Objects
 - [ ] Implementing custom `DataManipulators`
 - [ ] Storing Custom Data on existing `DataHolders`

*(existing, in the context of the above list, means 'existing in the SpongeAPI')*

Resource List:
 - [Original Data API PR](https://github.com/SpongePowered/SpongeAPI/pull/542)
 - [Value API Addtions PR](https://github.com/SpongePowered/SpongeAPI/pull/685)
 - ["How to use Data API 2.0" Forums Thread](https://forums.spongepowered.org/t/how-to-use-data-api-2-0/8925)

**Comment by Inscrutable** [comment]
"if a plugin wants to have a custom data manipulator, they need to register their DataManipulatorbuilder in GameInitializeServerEvent or whatever it is" - more info from gabizou

**Comment by saladoc** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/940/files Abstract Data in API.

**Comment by Tzky** [comment]
We need to add ``@ImplementationRequiredForTest`` to DataManipulators, as @gabizou added a parametarized ManipulatorTest. This applies to ``data manipulators that deal with objects that are entirely implementation dependent; i.e. anything that is a CatalogType, Text, Entity, ItemStack etc.``

**Comment by gabizou** [comment]
Just to add some examples of working custom data. The demo plugin will create `FakeData` and assign it to a `Player` who executed the `/fakeData` command and the `/validateData` command will check that the data exists on the `Player` who executed it. It's rudimentary but it exemplifies what is minimally required for custom data that persists properly between world loads and server restarts.

https://gist.github.com/gabizou/4219d260b00fe8624fa2

**Comment by Inscrutable** [comment]
Custom Data changes [here](https://github.com/SpongePowered/SpongeAPI/pull/1198/files#diff-6ddb89b71407d27dea43a2c31f93bab0R12) and [here](https://github.com/SpongePowered/SpongeAPI/pull/1198/files#diff-b7b5d3ae4a644dd27cce28c70981b1cbR16). "those two should basically suffice document writing" gabizou assures me...  
Also, if @saladoc is indisposed, we might need someone new to take control of this issue.

**Comment by Inscrutable** [comment]
We can also add #559 to the omnibus of Data stuff to get down with. SpongeDocs need someone who can help get this back on track. _Whomsoever shall yadda yadda ..._

**Comment by ST-DDT** [comment]
I might have a look at this once its gets a little bit colder...

**Comment by ST-DDT** [comment]
I didn't forget it (yet). I just pushed it further down the road. Somehow I feel like this issue is a ⛰⛰⛰.
(if anyone wants to go ahead...go ahead^^)

**Comment by Inscrutable** [comment]
This, and Inventories, are probably the two hardest subjects we have yet to tackle. It's been the downfall of one Editor in the past; what we really need is someone who is familiar with using it.
