### ISSUE TITLE
Track Enhancements of Debugging Documentation

### ISSUE THREAD

**Issue by Grauldon** [SpongePowered/SpongeDocs#793]
[SpongeDocs](https://github.com/SpongePowered/SpongeDocs/issues/356)

This issue is to track changes to SpongeDocs for adding debugging documentation and improving existing documents.

The list originated in SpongeDocs PR #661, and this issue will allow it to survive multiple PR's while making it easy to locate. Some additions have been made since the first PR, and more additions may occur over time. A reference to the PR completing a list item will be appended to that item.

- [x] post mixin class content output (#784)
- [x] Tools for decompiling the post mixing code (#784)
- [x] Suggest the creation of a test plugin (#784)
- [x] Common issues - Broken mixin (#784)
- [x] How to debug (#792)
- [ ] 1.) Common issues - NPEs
- [ ] 2.) Common issues - PhaseErrors
- [ ] 3.) Help with finding the error in your mixin based on the stacktrace
- [ ] 4.) Add [Using section](https://docs.spongepowered.org/stable/en/contributing/implementation/debugging/mixin.html#using) for using Minecraft Development plugin in [Debugging Mixin](https://docs.spongepowered.org/stable/en/contributing/implementation/debugging/mixin.html)
- [ ] 5.) Add [Bytecode Viewer](https://github.com/Konloch/bytecode-viewer) to the [Decompiling section](https://docs.spongepowered.org/stable/en/contributing/implementation/debugging/mixin.html#decompiling) in [Debugging Mixin](https://docs.spongepowered.org/stable/en/contributing/implementation/debugging/mixin.html)
- [ ] 6.) Update testplugins guidelines

**Comment by ImMorpheus** [comment]
Testplugins guidelines are outdated. See https://github.com/SpongePowered/SpongeCommon/pull/2195

**Comment by Grauldon** [comment]
> Testplugins guidelines are outdated. See [SpongePowered/SpongeCommon#2195](https://github.com/SpongePowered/SpongeCommon/pull/2195)

Thanks! I had forgotten about that.

**Comment by Grauldon** [comment]
Check on documentation requirements for [SpongeForge PR #2319](https://github.com/SpongePowered/SpongeForge/pull/2319).
