### ISSUE TITLE
[API-8] Docs Update Tracker

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeDocs#855]
We plan to update the existing API 7 docs to API 8.
This is a complete tree of the existing docs, all unchecked pages needs to be checked whether they need to be updated and be updated or replaced.
Feel free to add a comment regarding API features that have been added and are not documented at all yet.
If you wish to be in charge of the update for a particular page or section, please comment. We appreciate any help.
All PRs regarding the api-8 docs should target the https://github.com/SpongePowered/SpongeDocs/tree/api-8 branch.

- [x] index.rst
- [x] about
  - [x] assets.rst
  - [x] faq.rst
  - [x] future.rst
  - [x] glossary.rst
  - [x] history.rst
  - [x] index.rst
  - [x] introduction.rst
  - [x] license.rst
  - [x] posting.rst
  - [x] privacy.rst
  - [x] rules.rst
  - [x] staff.rst
  - [x] structure.rst
  - [x] tos.rst
- [ ] contributing
  - [x] guidelines.rst
  - [x] howtogit.rst
  - [ ] implementation
    - [ ] codestyle.rst (WIP)
    - [ ] datamanipulator.rst ⚠️ 🔥 
    - [ ] debugging
      - [x] faq.rst
      - [x] git.rst
      - [x] ide.rst
      - [x] index.rst
      - [ ] issues.rst 👻 #356 
      - [x] mixin.rst
      - [x] more.rst
      - [ ] testing.rst
      - [ ] tools.rst 👻 #356 
    - [x] git-implementation.rst
    - [x] index.rst
    - [ ] mixins.rst
    - [x] pr.rst
  - [ ] index.rst
  - [ ] porting.rst
  - [ ] spongedocs.rst
  - [ ] versioning.rst
- [ ] ore
  - [ ] api.rst
  - [ ] guidelines.rst
  - [ ] index.rst
  - [ ] publish.rst
  - [ ] routes
    - [ ] deploy-version.rst
    - [ ] download.rst
    - [ ] list-projects.rst
    - [ ] list-users.rst
    - [ ] list-versions.rst
    - [ ] project-version.rst
    - [ ] project.rst
    - [ ] user.rst
  - [ ] security.rst
- [ ] plugin
  - [x] api-versions.rst
  - [ ] assets.rst ⚠️
  - [x] bans.rst 
  - [x] blocks
    - [x] accessing.rst 
    - [x] concepts.rst
    - [x] index.rst
    - [x] modifying.rst 
    - [x] tileentities.rst 
    - [x] virtualblock.rst 
  - [ ] bookview.rst ⚠️
  - [ ] buildsystem.rst
  - [ ] commands
    - [x] arguments.rst 
    - [x] childcommands.rst 
    - [x] commandcallable.rst 
    - [x] creating.rst 
    - [ ] flags.rst ⚠️
    - [x] index.rst 
  - [ ] configuration ⚠️
    - [ ] index.rst ⚠️
    - [ ] loaders.rst ⚠️
    - [ ] nodes.rst ⚠️
    - [ ] serialization.rst ⚠️
  - [x] data
    - [x] customdatamanipulators.rst 
    - [x] index.rst 
    - [x] keys.rst 
    - [x] serialization.rst 
    - [x] transactions.rst 
  - [ ] database.rst ⚠️
  - [ ] debugging.rst
  - [x] economy
    - [x] basics.rst
    - [x] implementing.rst
    - [x] index.rst
    - [x] practices.rst
    - [x] using.rst 
  - [ ] effects.rst ⚠️
  - [ ] entities
    - [ ] ai.rst ⚠️
    - [ ] custom-ai.rst ⚠️
    - [ ] index.rst
    - [ ] modifying.rst ⚠️
    - [ ] spawning.rst
  - [x] event
    - [x] causes.rst 
    - [x] custom.rst 
    - [x] filters.rst 
    - [x] index.rst
    - [x] listeners.rst 
  - [ ] game-profile-manager.rst ⚠️
  - [ ] index.rst
  - [ ] injection.rst ⚠️
  - [ ] internals
    - [ ] access-transformers.rst
    - [ ] implementation.rst
    - [ ] index.rst
    - [ ] mcp-setup.rst
    - [ ] mcp.rst
    - [ ] mixins.rst
  - [ ] items
    - [ ] creating.rst ⚠️
    - [ ] index.rst
    - [ ] usage.rst ⚠️
  - [x] lifecycle.rst 
  - [x] logging.rst
  - [x] manager.rst 
  - [ ] metrics.rst ⚠️
  - [x] offline-userplayer-data.rst 
  - [ ] optional
    - [x] basic.rst
    - [x] index.rst
    - [ ] usage.rst
  - [ ] permissions.rst ⚠️
  - [ ] placeholders
    - [ ] creatingtokens.rst ⚠️
    - [ ] index.rst ⚠️
    - [ ] retrievingtext.rst ⚠️
  - [x] plugin-class.rst 
  - [x] plugin-identifier.rst
  - [x] plugin-meta.rst 
  - [x] practices
    - [x] bad.rst 
    - [x] best.rst
    - [x] index.rst
  - [ ] project
    - [ ] gradle.rst
    - [ ] index.rst
    - [ ] maven.rst
    - [ ] version-numbers.rst
  - [ ] ray-tracing.rst ⚠️
  - [ ] scheduler.rst ⚠️
  - [ ] services.rst
  - [ ] tab-lists.rst ⚠️
  - [x] text
    - [x] index.rst
    - [ ] messagechannels.rst 👻
    - [x] pagination.rst 
    - [ ] representations
      - [ ] configurate.rst 👻
      - [ ] formatting-code-legacy.rst 👻
      - [ ] plain 👻
      - [ ] index.rst 
      - [ ] json.rst 👻
    - [ ] templates.rst 👻
    - [x] text.rst 
  - [ ] trade-offers.rst ⚠️
  - [ ] tutorials.rst
  - [ ] wgen
    - [ ] customwgen.rst ⚠️
    - [ ] index.rst ⚠️
    - [ ] modifiers.rst ⚠️
  - [ ] workspace
    - [ ] eclipse.rst
    - [ ] idea.rst
    - [ ] index.rst
- [ ] preparing
  - [ ] git.rst
  - [ ] ide.rst
  - [ ] index.rst
  - [ ] jdk.rst
  - [ ] text.rst
- [ ] server
  - [ ] getting-started
    - [ ] bungeecord.rst
    - [ ] configuration
      - [ ] hocon.rst
      - [ ] index.rst
      - [ ] sponge-conf.rst
    - [ ] implementations
      - [ ] index.rst
      - [ ] spongeforge.rst
      - [ ] spongevanilla.rst
    - [ ] index.rst
    - [ ] jre.rst
    - [ ] launch-script.rst
    - [ ] migrating.rst
    - [ ] port-forward.rst
  - [ ] index.rst
  - [ ] management
    - [ ] bans.rst
    - [ ] exploit-patches.rst
    - [ ] index.rst
    - [ ] performance-tweaks.rst
    - [ ] permissions.rst
    - [ ] plugins.rst
    - [ ] whitelist.rst
  - [x] quickstart.rst
  - [ ] spongineer
    - [ ] bugreport.rst
    - [ ] commands.rst
    - [ ] debugging.rst
    - [ ] incompatible.rst
    - [ ] index.rst
    - [ ] logs.rst
    - [ ] properties.rst
    - [ ] troubleshooting.rst
- [ ] versions
  - [ ] filenames.rst
  - [ ] index.rst
  - [ ] legacy-versions.rst
  - [ ] versioning.rst

-----------

⚠️ = Broken imports/class/method references
🔥 = Might need a rewrite
👻 = This page is empty/awaiting content

Update-Tasks:

1. Check all pages
2. Fix imports/class/method references (Initial scan completed)
3. Fix code examples
4. Rewrite broken pages
5. Check the docs for errors
6. Goto 4

**Comment by ST-DDT** [comment]
FFR: Created branch https://github.com/SpongePowered/SpongeDocs/compare/api-8

**Comment by mosemister** [comment]
``plugin-class.rst`` im not seeing any broken imports nor class/method references. Could someone expand on whats wrong with it?
